# Generated by Django 4.2.1 on 2023-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='url_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
