# Generated by Django 4.1.3 on 2023-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
