# Generated by Django 4.2.1 on 2023-05-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0002_perfume_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='url_name',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=200),
        ),
    ]
