# Generated by Django 4.2.1 on 2023-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0006_alter_perfume_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='url_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
