# Generated by Django 4.2.1 on 2023-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0010_auto_20230509_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='url_name',
        ),
        migrations.AddField(
            model_name='perfume',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
