# Generated by Django 4.2.1 on 2023-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0011_remove_perfume_url_name_perfume_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='slug',
        ),
        migrations.AddField(
            model_name='perfume',
            name='url_name',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
