# Generated by Django 4.2.1 on 2023-05-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0013_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='le_bel_homme.Brand'),
            preserve_default=False,
        ),
    ]
