# Generated by Django 4.2.1 on 2023-05-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0015_alter_perfume_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='le_bel_homme.brand'),
        ),
    ]
