# Generated by Django 4.2.1 on 2023-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0018_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default='', null=True, to='le_bel_homme.ingredient'),
        ),
    ]
