# Generated by Django 4.2.1 on 2023-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('le_bel_homme', '0020_alter_perfume_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='le_bel_homme.ingredient'),
        ),
    ]
